### ISSUE TITLE
Meeting metadata is missing from logfile

### ISSUE THREAD

**Issue by OrenLederman** [HumanDynamics/openbadge-hub#6]
comments, location, moderator, etc. 

We might be able to keep these data only in the database in the future,  but for now it makes life easier and reduce risks of data loss

**Comment by JacksonKearl** [comment]
I was of the impression we didn't care for comments, location, and moderator in the new logging system? Thought they were Sloan-specific. Can you clarify what exactly we want in the log? I'll update to add description, location, moderator, and type, and we can either leave it like that or refine from there.

**Comment by JacksonKearl** [comment]
https://github.com/HumanDynamics/openbadge-hub/commit/6ee6d084d49efba997849dd8764b36f0a9623128
