### ISSUE TITLE
Allow adding badges to project in mid-meeting (low)

### ISSUE THREAD

**Issue by OrenLederman** [HumanDynamics/openbadge-hub#7]
The hub should update the list of known badges during the meeting. However, we want to make it to only receive updates in order to reduce data being sent. Is there a update_time field int eh people/badges table?

**Comment by JacksonKearl** [comment]
Implemented in https://github.com/HumanDynamics/openbadge-hub/commit/dbfeac91783b51b7d5b87071eb3b968ba41b0dd9

Can only add. Deletion not supported.
