### ISSUE TITLE
Allow editing meeting data before it ended (right now it fails because there is no end-date)

### ISSUE THREAD

**Issue by OrenLederman** [HumanDynamics/openbadge-hub#8]
from our emails:
Oren - I tried to update the list of badges of my project while there was a meeting going (via the admin screen), but it failed because the active meeting had no end date. Ideas on how to solve this? one option is to remove the list of meetings from the project view?

Jackson - I noticed that before. I thought I fixed it, but it's just adding a parameter to the field to say "blank=True" I believe.

**Comment by JacksonKearl** [comment]
https://github.com/HumanDynamics/OpenBadge-Server/commit/fc58af38fef4e51f02eda225e9fd7a74ae4fa369

**Comment by JacksonKearl** [comment]
Fixed server-side.
