### ISSUE TITLE
Meeting not marked as "ended" for a long time

### ISSUE THREAD

**Issue by OrenLederman** [HumanDynamics/openbadge-hub#9]
A 1.5 hours meeting was not marked as completed for over an hour. I create a short meeting to try and force the first one to sync, but that meeting too took some time to be marked as completed.

Interestingly, the last (short) meeting was marked as completed first, and only after some time the long meeting was marked as completed.

My guess - perhaps the app was trying to re-send the meeting data (because of gaps?). This action might fail, or take some time if it's a long meeting (large file)

**Comment by JacksonKearl** [comment]
https://github.com/HumanDynamics/openbadge-hub/commit/c6201f8c39c54982399efb18d5c2ffcd76a42575
Possible fix.
